# Generated by Django 4.1.4 on 2022-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_delete_videoproxy_videopublishedproxy_video_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
