# Generated by Django 4.1.4 on 2022-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_created_video_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
